### ISSUE TITLE
Unable to add plugin for Flutter Master Channel 0.5.2

### ISSUE THREAD

**Issue by LiveRock** [btastic/flutter_native_image#10]
Hi 
I am using Flutter Master channel 0.5.2
Got error:
Because renalbase depends on flutter_native_image from git which requires Flutter SDK version >=0.1.0 <=0.4.4, version solving failed.

when trying to add in my pub file.

Please help.

**Comment by btastic** [comment]
Fixed thanks to @acidjazz via https://github.com/btastic/flutter_native_image/pull/11
