### ISSUE TITLE
Error when calling compressImage

### ISSUE THREAD

**Issue by RobertBrunhage** [btastic/flutter_native_image#14]
Hey!

Tried your lib for compressing my image on android but when I call the compressImage method like this:

    File compressedFile = await FlutterNativeImage.compressImage(imageFile.path,
        quality: 60, percentage: 60);

it results in this error:

E/MethodChannel#flutter_native_image(10518): Failed to handle method call
E/MethodChannel#flutter_native_image(10518): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#flutter_native_image(10518): 	at com.example.flutternativeimage.FlutterNativeImagePlugin.onMethodCall(FlutterNativeImagePlugin.java:51)
E/MethodChannel#flutter_native_image(10518): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter_native_image(10518): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
E/MethodChannel#flutter_native_image(10518): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_native_image(10518): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#flutter_native_image(10518): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#flutter_native_image(10518): 	at android.app.ActivityThread.main(ActivityThread.java:6798)
E/MethodChannel#flutter_native_image(10518): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_native_image(10518): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/MethodChannel#flutter_native_image(10518): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/flutter (10518): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (10518): PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)
E/flutter (10518): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
E/flutter (10518): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (10518): <asynchronous suspension>
E/flutter (10518): #2      FlutterNativeImage.compressImage (package:flutter_native_image/flutter_native_image.dart:15:31)
E/flutter (10518): <asynchronous suspension>
E/flutter (10518): #3      _CreatePlantState._addPlantToUser (package:planti/Plant/CreatePlant.dart:180:52)
E/flutter (10518): <asynchronous suspension>
E/flutter (10518): #4      _CreatePlantState.checkSubscription (package:planti/Plant/CreatePlant.dart:217:13)
E/flutter (10518): <asynchronous suspension>
E/flutter (10518): #5      _CreatePlantState.build.<anonymous closure>.<anonymous closure> (package:planti/Plant/CreatePlant.dart:64:38)
E/flutter (10518): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
E/flutter (10518): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
E/flutter (10518): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (10518): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (10518): #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
E/flutter (10518): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (10518): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (10518): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (10518): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter (10518): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (10518): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (10518): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (10518): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (10518): #19     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (10518): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)

**Comment by btastic** [comment]
Hey thank you for reporting. I think this is a Bug introduced with the targetWidth and targetHeight feature. I might have a look at it in a bit.

**Comment by btastic** [comment]
I just pushed something that should fix it:

https://github.com/btastic/flutter_native_image/commit/6226d2196bd7e8f8c0b13013e0e5c5b13b186f78

Can you try and give me some feedback?

Thanks

**Comment by RobertBrunhage** [comment]
Still get the same error it seems

**Comment by btastic** [comment]
Try removing the library from your pubspec.yml, save it (so it gets removed), then add it again (so it gets installed again). Doesn't sound like you have the latest version.

**Comment by RobertBrunhage** [comment]
Ahh okey, fixed that but that gave me error for the newly added code.

C:\Users\Robert\AppData\Roaming\Pub\Cache\git\flutter_native_image-5b2e1c9e27c480dd28c38f9a36fb34ee01bd6c29\android\src\main\java\com\example\flutternativeimage\FlutterNativeImagePlugin.java:51: error: incompatible types: Object cannot be converted to int
      int targetWidth = call.argument("targetWidth") == null ? 0 : call.argument("targetWidth");
                                                             ^
C:\Users\Robert\AppData\Roaming\Pub\Cache\git\flutter_native_image-5b2e1c9e27c480dd28c38f9a36fb34ee01bd6c29\android\src\main\java\com\example\flutternativeimage\FlutterNativeImagePlugin.java:52: error: incompatible types: Object cannot be converted to int
      int targetHeight = call.argument("targetHeight") == null ? 0 : call.argument("targetHeight");
                                                               ^
2 errors

**Comment by btastic** [comment]
There was an issue that I did not cast the call.argument to an int before assigning it: https://github.com/btastic/flutter_native_image/commit/77b06ad03dc0bda3708e3987327d2b1479c29291

Please try again

**Comment by RobertBrunhage** [comment]
Sweet it works now!

Will test it more though out the day and see if everything works correctly!

Thanks a lot for the fast fixes

**Comment by btastic** [comment]
Cool, thanks for your feedback.

Will leave this open for the next 24 hours or so.

Thanks again
