### ISSUE TITLE
Doesn't resize image

### ISSUE THREAD

**Issue by pablote** [btastic/flutter_native_image#16]
I'm testing this out, and it doesn't seem to be resizing images at all, they come out with the same resolution. There's some logs on the console, not sure if related:

my code:
```
static Future<File> convertToJpeg(File imageFile) async {
    var imageProps = await FlutterNativeImage.getImageProperties(imageFile.path);

    print('convertToJpeg: image width = ${imageProps.width}');
    print('convertToJpeg: image height = ${imageProps.height}');
    if (imageProps.width > maxImageWidth) {
      var start = DateTime.now();
      print('convertToJpeg: resizing image');
      var resizedFile = await FlutterNativeImage.compressImage(imageFile.path, quality: 95, targetWidth: maxImageWidth);
      
      print('convertToJpeg: done resizing took=${DateTime.now().difference(start).inMilliseconds}');

      return resizedFile;
    } else {
      print('convertToJpeg: returning image as is');
      return imageFile;
    }
  }
```

console output:
```
I/flutter (23011): convertToJpeg: image width = 480
I/flutter (23011): convertToJpeg: image height = 480
I/flutter (23011): convertToJpeg: resizing image
I/ExifInterface_JNI(23011): Raw image not detected
I/ExifInterface_JNI(23011): Raw image not detected
I/flutter (23011): convertToJpeg: done resizing took=82
```

thanks!

**Comment by btastic** [comment]
Might be that Images that are smaller than 1500w or 1500h won't get resized.

This is an old thing I had in the library when I was using it on my own.

I might throw this out and check it in flutter via the new image properties we can now read.

Any help is welcome:

https://github.com/btastic/flutter_native_image/blob/72a14a382aec482cb044bf76087634a641301a73/android/src/main/java/com/example/flutternativeimage/FlutterNativeImagePlugin.java#L65

https://github.com/btastic/flutter_native_image/blob/72a14a382aec482cb044bf76087634a641301a73/ios/Classes/FlutterNativeImagePlugin.m#L51

Those lines need to be removed. Then it will work.

**Comment by pablote** [comment]
Cool, I've tested it up with larger images and it works fine. No longer an issue for me, it's just the emulator camera that generates those small images, but the regular pictures I need to handle are much larger, so this is fine.

**Comment by thedejifab** [comment]
@btastic, I get the `Raw image not detected error`. Any help?
