### ISSUE TITLE
please add support to Dart SDK version is 2.1.0-dev.0.0 

### ISSUE THREAD

**Issue by sam0610** [btastic/flutter_native_image#21]
the following error occurred with master build:

depends on flutter_native_image from git which requires SDK version >=1.0.0 <2.0.0, version solving failed.

**Comment by LiveRock** [comment]
Yes, please add support for SDK version 2.1.0-dev.0.0.flutter-be6309690f.

**Comment by btastic** [comment]
Let me know if it works now: https://github.com/btastic/flutter_native_image/commit/570cafee663b360c27be9a002d15bda020332f5b

**Comment by LiveRock** [comment]
seems ok now.

**Comment by btastic** [comment]
Thank you!
