### ISSUE TITLE
Crop doesn't work on iOS

### ISSUE THREAD

**Issue by dmjones** [btastic/flutter_native_image#22]
I'm trying to square crop an image using the following code:

```dart
Future<String> _resizePhoto(String filePath) async {
    try {
      ImageProperties properties =
          await FlutterNativeImage.getImageProperties(filePath);

      print("Width: ${properties.width}, Height: ${properties.height}");

      int width = properties.width;
      var offset = (properties.height - properties.width) / 2;

      print("Offset = ${offset.round()}");

      File croppedFile = await FlutterNativeImage.cropImage(
          filePath, 0, offset.round(), width, width);

      // Check it worked
      properties =
      await FlutterNativeImage.getImageProperties(croppedFile.path);
      print("Width: ${properties.width}, Height: ${properties.height}");

      return croppedFile.path;
    } catch (e) {
      print(e);
    }
  }
```

Instead of getting a square cropped image, the image is shown sideways with some of the top-left of the image shown. The printed output suggests things have gone wrong:

```
flutter: Width: 720, Height: 1280
flutter: Offset = 280               // This seems correct. Cutting 280 will square the image
flutter: Width: 720, Height: 440    // This correlates to what I see in the final image, 
                                    // but I expected w720 x h720
```

Am I using this function correctly?

FYI - the source of my image is a camera capture, taken using the [camera](https://pub.dartlang.org/packages/camera) package.

**Comment by btastic** [comment]
Hmm I didn't write that function and I don't have a lot of time to investigate right now. Maybe @a-leblond can chime in and see if there is anything wrong? Thanks!

**Comment by a-leblond** [comment]
Hi !
 
It seems weird, I use this function on iOS and Android in one of my project to square crop images and it works fine on both.
I don't see anything wrong with your code ... Could you try this and tell us if it works ? It's the code I use in my app :

      var imgProperties = await FlutterNativeImage.getImageProperties(widget.imagefile.path);
      var croppedImage;
      if(imgProperties.width > imgProperties.height)
        croppedImage = await FlutterNativeImage.cropImage(widget.imagefile.path,
            (imgProperties.width~/2)-(imgProperties.height~/2), 0,
            imgProperties.height, imgProperties.height);
      else
        croppedImage = await FlutterNativeImage.cropImage(widget.imagefile.path,
            0, (imgProperties.height~/2)-(imgProperties.width~/2),
            imgProperties.width, imgProperties.width);

**Comment by dmjones** [comment]
Thanks for sharing your code. I get the same result when using your code.

At the moment, my best guess is that it's somehow related to EXIF rotation data. AIUI, if the rotation data is ignored, the image will appear sideways. I'm wondering if bits of the library code respect the EXIF data and bits don't.

I'll do some further digging with 'normal' images and will report back.

**Comment by dmjones** [comment]
Indeed, when I test with a static image that definitely isn't EXIF rotated, your code (and mine) works fine.

**Comment by a-leblond** [comment]
Hmmmm I had some issues with the EXIF and [image](https://pub.dartlang.org/packages/image), so I use flutter_native_image in my app and it works fine both with the camera and static images, on Android and iOS.

Maybe it's the camera package you are using ? I use [image_picker](https://pub.dartlang.org/packages/image_picker) to take photo with the camera, you could give it a try.

I'll look deeper in the flutter_native_image code to see if there is something wrong this week.

**Comment by dmjones** [comment]
I've started migrating to image_picker, which should avoid this problem. (I'm also moving away from square cropped images).

So I'm happy to close this, as my need has gone away. But leaving it open for now in case others are interested...
