### ISSUE TITLE
Why only downscaling if width/height < 1500

### ISSUE THREAD

**Issue by lschmierer** [btastic/flutter_native_image#28]
Is there any reason why the downsampling is only applied to images where width or height is > 1500 pixels?
https://github.com/btastic/flutter_native_image/blob/master/ios/Classes/FlutterNativeImagePlugin.m#L51

I have images that are a little smaller (720x1080) that I want to resize. In fact I dont even need to resize at all, but just applying the exif orientation changes as Flutter currently isnt able to display them correctly (https://github.com/flutter/flutter/issues/24455).

**Comment by btastic** [comment]
Closed via https://github.com/btastic/flutter_native_image/pull/29
