### ISSUE TITLE
Compressing the same image in different sizes results in file overwrite

### ISSUE THREAD

**Issue by stevenspiel** [btastic/flutter_native_image#40]
Great plugin! Thanks for you work on this.

One thing I'm seeing is that when I compress the same image multiple times (with different compression parameters), the same "_compressed.jpg" ending is added and the previous file is overwritten.

My specific use case is that I generate different sizes and I'd like to upload them asynchronously, but there's no telling which size is which because _compressed.jpg is a moving target.

In the meantime, I can upload the files synchronously, but it's a gotcha that might be worth noting in the README.

**Comment by btastic** [comment]
Sorry for leaving you hanging. However, I don't quite understand your issue. Can you please provide sample code or something? Thank you

**Comment by snadon** [comment]
I'm having a similar issue.

My use case is simple:

1. Take a picture
2. Compress the picture
3. Resize to create a thumbnail

At step 3, the generated file `foo_compressed.jpg` overwritten the first generated one from step 2. So if I upload in the background it ends up uploading the thumbnail twice.

Also, my first attempt to work around this didn't work. I copied the image under a sub-directory like `/thumbnails` but it still ended up overwriting. The generated `foo_compressed.jpg` file is written directly under `/tmp` without adding the sub-directory.

My second work around didn't work either. I named the thumbnail `foo_t.jpg` and the plugin ended up replacing `_t.jpg` with `_compressed.jpg`.

My third try worked! I named the thumbnail `foo.thumb.jpg` and the generated file ended up being `foo.thumb_compressed.jpg`.

Would it be convenient to add an optional parameter to `compressImage` like `outputPath`?

Also, what is the fastest way of duplicating an image with Flutter?

Thanks!

**Comment by snadon** [comment]
I just noticed that on Android the compressed file is something like `_compressed4654761654884463391.jpg` and not `_compressed.jpg`.

**Comment by btastic** [comment]
I'd like to have a look at that. Mind sharing a simplified version of code to understand the issue better?

**Comment by stevenspiel** [comment]
@snadon It must be just an iOS issue, then. 

@btastic  something like this:

```dart
static String IMAGE_URL = 'https://i.dailymail.co.uk/i/pix/2015/09/01/18/2BE1E88B00000578-3218613-image-m-5_1441127035222.jpg'

void main() async {
  final Response response = await get(IMAGE_URL);
  final Directory documentDirectory = await getApplicationDocumentsDirectory();
  final String filePath = join(documentDirectory.path, 'foo.png');
  final File file = File(filePath);

  file.writeAsBytesSync(response.bodyBytes);
  
  assert(await file.exists(), 'file at $filePath should exist');

  List<File> compressedFiles = await Future.wait([
    FlutterNativeImage.compressImage(filePath, quality: 80),
    FlutterNativeImage.compressImage(filePath, quality: 40),
  ]);

  assert(compressedFiles[0].path != compressedFiles[1].path); // currently failing on iOS
}
```

Even though the compression itself may be quick, if I wanted to do something like upload the files asynchronously, the compressedFile is overwritten.

**Comment by stevenspiel** [comment]
opened https://github.com/btastic/flutter_native_image/pull/44 that fixes this

**Comment by btastic** [comment]
Sorry for not being active as much as I would like to be.
