### ISSUE TITLE
Crashing on iOS real devices

### ISSUE THREAD

**Issue by afnx** [btastic/flutter_native_image#49]
Hello, I've tested this package on both iOS and Android real devices. While it is slowly working on Android, it does not work on iOS at all. It always crashes on iOS real devices and same for simulators.

**Comment by btastic** [comment]
I am getting a mac to reproduce these issues.

**Comment by btastic** [comment]
I can't repro the crashing on iOS. Can you give me a repository with the code that reproduces your error?

**Comment by btastic** [comment]
Any error messages / logs / reproduction code?

**Comment by kgrigorian** [comment]
```
await cameraController.takePicture(path);
                    File file = await bloc.compress(path);
                    var newFileSize = await file.length();
                    print('new file size is $newFileSize');

 Future<File> compress(String path) async {
    var initialFile = File(path);
    var fileSize = await initialFile.length();
    print('initial file size is $fileSize');
    if (fileSize > MAX_FILE_SIZE) {
      return await FlutterNativeImage.compressImage(path);
    } else {
      return initialFile;
    }
  }
```

**Comment by btastic** [comment]
I am on an iPhone 7 with iOS 12.3.1. I can't get an iPhone X right now to confirm this. Sorry.

**Comment by btastic** [comment]
If you could get me any logs or error messages or anything, that would be greatly appreciated.

**Comment by btastic** [comment]
Any information about this issue?
