### ISSUE TITLE
Failing while building on Bitrise

### ISSUE THREAD

**Issue by thedejifab** [btastic/flutter_native_image#50]
Hi @btastic , I'm using the Bitrise CI tool to generate iOS artifacts for my application since I don't have a Mac, and here's the log of the error I encounter on getting to the flutter-build stage:

Downloading ios tools...                                            2.7s
Downloading ios-profile tools...                                    1.4s
Downloading ios-release tools...                                    1.1s
Building com.adap.mobile for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: H55G3YSH5P
Running pod install...                                              6.7s
Running Xcode build...                                          
Xcode build done.                                           43.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/FlutterNativeImagePlugin.m:77:19: warning: unused variable 'fileName' [-Wunused-variable]
            NSString *fileName = [[fileArgument lastPathComponent] stringByDeletingPathExtension];
                      ^
    1 warning generated.
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Alpha.m:97:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (CGImageRef)newBorderMask:(NSUInteger)borderSize size:(CGSize)size {
    ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Alpha.m:10:1: note: method 'newBorderMask:size:' declared here
    - (CGImageRef)newBorderMask:(NSUInteger)borderSize size:(CGSize)size;
    ^
    1 warning generated.
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:151:13: warning: enumeration values 'UIImageOrientationUp' and 'UIImageOrientationUpMirrored' not handled in switch [-Wswitch]
        switch (self.imageOrientation) {
                ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:151:13: note: add missing switch cases
        switch (self.imageOrientation) {
                ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:171:13: warning: 4 enumeration values not handled in switch: 'UIImageOrientationUp', 'UIImageOrientationDown', 'UIImageOrientationLeft'... [-Wswitch]
        switch (self.imageOrientation) {
                ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:171:13: note: add missing switch cases
        switch (self.imageOrientation) {
                ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:110:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (UIImage *)resizedImage:(CGSize)newSize
    ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:12:1: note: method 'resizedImage:transform:drawTransposed:interpolationQuality:' declared here
    - (UIImage *)resizedImage:(CGSize)newSize
    ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:148:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (CGAffineTransform)transformForOrientation:(CGSize)newSize {
    ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:16:1: note: method 'transformForOrientation:' declared here
    - (CGAffineTransform)transformForOrientation:(CGSize)newSize;
    ^
    4 warnings generated.
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+RoundedCorner.m:60:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (void)addRoundedRectToPath:(CGRect)rect context:(CGContextRef)context ovalWidth:(CGFloat)ovalWidth ovalHeight:(CGFloat)ovalHeight {
    ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+RoundedCorner.m:11:1: note: method 'addRoundedRectToPath:context:ovalWidth:ovalHeight:' declared here
    - (void)addRoundedRectToPath:(CGRect)rect context:(CGContextRef)context ovalWidth:(CGFloat)ovalWidth ovalHeight:(CGFloat)ovalHeight;
    ^
    1 warning generated.
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/FlutterNativeImagePlugin.m:77:19: warning: unused variable 'fileName' [-Wunused-variable]
            NSString *fileName = [[fileArgument lastPathComponent] stringByDeletingPathExtension];
                      ^
    1 warning generated.
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Alpha.m:97:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (CGImageRef)newBorderMask:(NSUInteger)borderSize size:(CGSize)size {
    ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Alpha.m:10:1: note: method 'newBorderMask:size:' declared here
    - (CGImageRef)newBorderMask:(NSUInteger)borderSize size:(CGSize)size;
    ^
    1 warning generated.
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:96:99: warning: enum values with underlying type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
                [NSException raise:NSInvalidArgumentException format:@"Unsupported content mode: %d", contentMode];
                                                                                                 ~~   ^~~~~~~~~~~
                                                                                                 %ld  (long)
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:151:13: warning: enumeration values 'UIImageOrientationUp' and 'UIImageOrientationUpMirrored' not handled in switch [-Wswitch]
        switch (self.imageOrientation) {
                ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:151:13: note: add missing switch cases
        switch (self.imageOrientation) {
                ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:171:13: warning: 4 enumeration values not handled in switch: 'UIImageOrientationUp', 'UIImageOrientationDown', 'UIImageOrientationLeft'... [-Wswitch]
        switch (self.imageOrientation) {
                ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:171:13: note: add missing switch cases
        switch (self.imageOrientation) {
                ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:110:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (UIImage *)resizedImage:(CGSize)newSize
    ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:12:1: note: method 'resizedImage:transform:drawTransposed:interpolationQuality:' declared here
    - (UIImage *)resizedImage:(CGSize)newSize
    ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:148:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (CGAffineTransform)transformForOrientation:(CGSize)newSize {
    ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+Resize.m:16:1: note: method 'transformForOrientation:' declared here
    - (CGAffineTransform)transformForOrientation:(CGSize)newSize;
    ^
    5 warnings generated.
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+RoundedCorner.m:60:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (void)addRoundedRectToPath:(CGRect)rect context:(CGContextRef)context ovalWidth:(CGFloat)ovalWidth ovalHeight:(CGFloat)ovalHeight {
    ^
    /Users/vagrant/.pub-cache/git/flutter_native_image-426996b810c8ff3899a6109b65bdab143652e875/ios/Classes/UIImage+RoundedCorner.m:11:1: note: method 'addRoundedRectToPath:context:ovalWidth:ovalHeight:' declared here
    - (void)addRoundedRectToPath:(CGRect)rect context:(CGContextRef)context ovalWidth:(CGFloat)ovalWidth ovalHeight:(CGFloat)ovalHeight;
    ^
    1 warning generated.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Code Signing Error: No profiles for 'com.adap.mobile' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.adap.mobile'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.

**Comment by thedejifab** [comment]
By the way, I get same issue when I try to use Codemagic so it's not a Bitrise-specific thing

**Comment by btastic** [comment]
`Code Signing Error: No profiles for 'com.adap.mobile' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.adap.mobile'. Automatic signing is disabled and unable to generate a profile`

I dont know how the CI works, but you need a developer account to build for iOS.

**Comment by btastic** [comment]
I built my apps with microsofts appcenter and that works well.

**Comment by btastic** [comment]
Any news on this?

**Comment by thedejifab** [comment]
No. Guess it will be fine to close the issue.
