### ISSUE TITLE
get packages fails

### ISSUE THREAD

**Issue by francishero** [btastic/flutter_native_image#52]
Could not find a file named "pubspec.yaml" in https://github.com/btastic/flutter_native_image.git 8661d8aecd626f7f57ccbcb735553edc05a2e713.

**Comment by Scofielddd** [comment]
dev_dependencies:
--flutter_test:
-----sdk: flutter
--flutter_native_image:
-----git: https://github.com/btastic/flutter_native_image.git

**Comment by DavidPineda** [comment]
@francishero pudiste solucionar este error ?

**Comment by heromiyo** [comment]
fixed

**Comment by btastic** [comment]
Is this issue still a thing?

**Comment by k2evil** [comment]
> Is this issue still a thing?

I don't know why this is happening but after I've add the library to the `pubspec.yaml` file, And the `packages get` is run successfully everytime, but when I import the `flutter_native_image/flutter_native_image.dart` file, it says that target doesn't exist.

**Comment by btastic** [comment]
I just installed it to a fresh project. It uses 

`import 'package:flutter_native_image/flutter_native_image.dart';`

as an import.

**Comment by k2evil** [comment]
> I just installed it to a fresh project. It uses
> 
> `import 'package:flutter_native_image/flutter_native_image.dart';`
> 
> as an import.
> 
> ![Code_2019-10-22_21-38-38](https://user-images.githubusercontent.com/6894999/67324880-8cafe700-f514-11e9-9c38-dc45b961385d.png)

It's turned out that was a Android Studio problem.
