### ISSUE TITLE
getExternalCacheDir() called on null when added to native android app

### ISSUE THREAD

**Issue by adithyaxx** [btastic/flutter_native_image#57]
I am adding a flutter module using flutter_native_image as a dependency to a native android app. I get the error in the title when the android app is run. It seems like activity is always null which causes this issue.

I suspect this is something to do with v2 embedding and a migration of this plugin could possibly fix the issue. I'll open a PR if I manage to fix it.

**Comment by bosssanovar** [comment]
@btastic 
I am suffering from similar errors when running in the background Isolate.
I tried the fix made by adithyaxx and it worked fine.
In my use case, I am bothered by this and # 47. So please understand this P.R. and solve it.

**Comment by btastic** [comment]
I just merged and published the PR for v2 embedding. Thanks for the contribution!
