### ISSUE TITLE
quality or percentage Which is the compression of the picture

### ISSUE THREAD

**Issue by misskter** [btastic/flutter_native_image#61]
When I use 100 quality and percentage, the compressed image is larger than the original image, so I want to know what the meaning of quality and percentage represents?

**Comment by btastic** [comment]
Quality is between 0 and 100 and influences how the compression algorithm is working.
Percentage is how much you want to resize the image. If you have like a 500x500 image and resize it by 50 percent, it will be 250x250.

I don't think it is an actual use case of using 100 quality and percentage. The resizing / compression algorithm might be doing weird things to the original image. I suppose the "quick fix" would be to return the original image. However, I don't see this as an issue.

If you have more questions, feel free to reopen the issue.
