### ISSUE TITLE
Update version on pub

### ISSUE THREAD

**Issue by MisterJimson** [btastic/flutter_native_image#65]
The last update on pub is from June 5th. 

Using git dependencies in pubspec should be avoided for consistent results, especially when you don't have control of the repo.

**Comment by btastic** [comment]
Hey, 

I didnt even know this package was available on pub. I did not publish it there. I am going to contact to pub creator and see what I can do

**Comment by btastic** [comment]
Version 0.0.5 is now available on pub.dev

https://pub.dev/packages/flutter_native_image

Thanks for bringing this to my attention.

And thanks to @gabuldev for answering and making it easy for me :)
