### ISSUE TITLE
compressImage doesn't work if no permission

### ISSUE THREAD

**Issue by a-leblond** [btastic/flutter_native_image#7]
Hi, 

the compressImage function doesn't work in some cases if the user doesn't have the write external storage permission on android. The output image is created in same directory as the original one, so it can be easily fixed by creating the output image in the ExternalCacheDir as a TemporaryFile.

I can pull a hotfix this week, I should have time to do this.

**Comment by btastic** [comment]
Yea thats a good one, too. About the permissions: I think that this library should not care about permissions, as the app usually should do that. By putting the image to an external cache directory, we can midigate this issue in the first place.

Thank you so much!

**Comment by a-leblond** [comment]
I agree, and less permission is better for an app ! 

No problem i'll do that :)
