### ISSUE TITLE
Exif information not preserving.

### ISSUE THREAD

**Issue by mBosamiya** [btastic/flutter_native_image#83]
Hello Author,

I am not able to get the location information of image after compression using this library.

See attached Information dialog for both **Original & Compressed** image.

Here is the code:

`final compressedImage = await FlutterNativeImage.compressImage(file.path,percentage: 50);`

![Screenshot 2021-04-16 at 3 50 52 PM](https://user-images.githubusercontent.com/67785793/115011150-e73cc000-9ecb-11eb-864f-82dfeaa6e34d.png)
![Screenshot 2021-04-16 at 3 51 28 PM](https://user-images.githubusercontent.com/67785793/115011162-ead04700-9ecb-11eb-925d-ae4075c054ea.png)

**Comment by btastic** [comment]
Duplicate https://github.com/btastic/flutter_native_image/issues/31
