### ISSUE TITLE
.png file has blackbackground after crop

### ISSUE THREAD

**Issue by netgfx** [btastic/flutter_native_image#88]
I'm doing this:

```
final ByteData data = await rootBundle.load('assets/monster1.png');
String dir = (await getApplicationDocumentsDirectory()).path;
File path = await writeToFile(data, '$dir/monster1.png');
File croppedFile = await uiImage.FlutterNativeImage.cropImage(path.path, 0, 0, 192, 212);
  ```
  if I convert `Uint8List bytes = croppedFile.readAsBytesSync();` to an image I get the image (cropped) with a black background.
  However if I do `Uint8List bytes = path.readAsBytesSync();` (which is the saved pre-crop image) I get the un-cropped image with transparent background.
  
 Is there anything I can do to maintain the transparent background?

**Comment by netgfx** [comment]
I believe this is the culprit here:
```
bmp.compress(Bitmap.CompressFormat.JPEG, 100, bos);
            bmp.recycle();
            OutputStream outputStream = null;
            try {
                String outputFileName = File.createTempFile(
                        getFilenameWithoutExtension(file).concat("_cropped"),
                        ".jpg",
                        context.getExternalCacheDir()
                ).getPath();
  ```
  maybe it should check the file extension and switch between .jpg and .png

**Comment by netgfx** [comment]
opened a PR https://github.com/btastic/flutter_native_image/pull/89

**Comment by btastic** [comment]
I just uploaded a new version to pub.dev (0.0.6+1). Let me know if it works and then close this issue. 

Thanks again!

**Comment by netgfx** [comment]
works nicely! thanks!
