### ISSUE TITLE
Crop image on Ios doesn't work

### ISSUE THREAD

**Issue by Giacomo1993** [btastic/flutter_native_image#90]
Hi @aryzhov @netgfx @acidjazz @strokine @greymag, i.m working on my app and I need to implement a library in order to make a square center crop of an image captured from the camera.  
In android, it works correctly but in Ios, it trows a "Platform Exception" with this error:
![error image](https://user-images.githubusercontent.com/68004050/134922092-da9e886e-c745-45b1-b3b0-a42df05025dc.png)
 "

I used this method in order to crop the image: 

ImageProperties properties =
    await FlutterNativeImage.getImageProperties(filePath);

  int height = properties.height;
    var offset = (properties.width - properties.height) / 2;

    File croppedFile = await FlutterNativeImage.cropImage(
        filePath,  offset.toInt(), 0, height, height);

Can you help me?

**Comment by greymag** [comment]
Hey. Check your width/height. Is it possible that width less than height?

**Comment by Giacomo1993** [comment]
yes, I'm sorry! I resolved with this https://github.com/btastic/flutter_native_image/issues/22#issuecomment-416072112
